import Place from "./place";

export default interface Survey {
    surveyData: object;
    cypher: object;
    age: string;
    bestApp: Array<string>;
    "channel": string;
    "countFriends": number;
    "countPhysical": number;
    "countSex": number;
    "covidTestPositive": string;
    "english": boolean;
    "gender": string;
    "groupSex": string;
    "hivPrep": string;
    "hivStatus": string;
    "hivSuppressed": string;
    "homeCensusTract": string;
    "lastQuestion": string;
    "mapGroupSex": string;
    "monkeypoxCare": string;
    "monkeypoxTest": string;
    "monkeypoxVaccine": string;
    "monkeypoxDiagnosis": string;
    "places": Array<Place>,
    "publicId": string;
    "raceAsian" :boolean;
    "racePacific":boolean;
    "raceBlack": boolean;
    "raceLatinx": boolean;
    "raceOther": boolean;
    "anotherQuestion": string;
    "raceWhite": boolean;
    "referrerEnglish": boolean;
    "referrerID": string;
    "referralType": number;
    "returnParticipant": string;
    "sex": string;
    "sexOrientation": string;
    "symptomSorePenis": boolean;
    "symptomBackAche": boolean;
    "symptomBodyRash": boolean;
    "symptomChills": boolean;
    "symptomExhaustion": boolean;
    "symptomFacialRash": boolean;
    "symptomFever": boolean;
    "symptomHeadache": boolean;
    "symptomMouth": boolean;
    "symptomMuscleAche": boolean;
    "symptomOther": boolean;
    "symptomRectalDiscomfort": boolean;
    "symptomSoreThroat": boolean;
    "symptomSoresAnus": boolean;
    "symptomSwollenGlands": boolean;
    "travelTime": number;
    "vaccinationDate": string;
    "userName": string;
    "userId":string;
}